### ISSUE TITLE
Acabar el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/dorcas-s3-evaluacion-intermedia-mariavioleta1417#1]
Te dejo algunas pistas para que puedas mejorarlo:

- Añadir carpeta components para que todo esté más organizadito.
- Mejorar la indentación.
- Añadir una etiqueta `main`!
- Añadir keys en los listados (https://reactjs.org/docs/lists-and-keys.html)
- Animarte a hacer destructuring para no escribir tantas veces `this.props`
- Instalar la librería `prop-types` y usarla para comprobar el tipado js de las props.
- Acabar el css
- Eliminar archivos que no usamos (App.test.js, logo.svg...)

También te recomiendo publicar en Github Pages para practicar ;)

A por ello!

**Comment by mariavioleta1417** [comment]
creo que ya está, y además he puesto las skills es mayúsculas y la primera letra del nombre en mayúscula 😌😌😌

**Comment by nasivuela** [comment]
Buen trabajo!!!!
